#!/usr/bin/env bash
#Setting the HTTP header
# shellcheck disable=SC2154
sudo apt-get update
sudo apt-get -y install nginx
string2="http {\\n\\tadd_header X-Served-By \'$HOSTNAME\';"
sudo sed -i "s/http {/$string2/" /etc/nginx/nginx.conf
sudo service nginx reload
sudo service nginx restart
