#!/usr/bin/env bash
#Setting the Loadbalancer HAProxy & Frontend
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get -y update
sudo apt-get install haproxy=1.7.\* -y
echo "frontend http_front
         bind *:80
         default_backend http_rear
      backend http_rear
         balance roundrobin
            server web-01 35.229.25.153:80 check
            server web-02 34.73.159.23:80 check" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy start
