#!/usr/bin/env bash
# This script print the current process
caza()
{
	rm /var/run/holbertonscript.pid
	i=2
}
echo $$ > /var/run/holbertonscript.pid
i=0
while [ $i -le 1 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"' 15
	trap 'echo "Y U no love me?!"' 2
	trap caza 3 15
done
