#!/usr/bin/env bash
# FizzBuzz
i=1
a=i % 3
b=i % 5
while [ $i -lt 20 ]
do
    if (a==0)
    then
	if (b==0)
	then
	    echo "FizzBuzz"
	else
	    echo "Fizz"
	fi
    else
	if (b==0)
	then
	    echo "Buzz"
	else
	    echo $i
	fi
    fi
    ((i++ ))
done
