#!/usr/bin/env bash
# Display 10 times Holberton School and Hi in pos 9
i=1
while [ $i -lt 11 ]
do
    if [ $i -eq 4 ]
    then
	echo "bad luck"
    elif [ $i -eq 8 ]
	then
	    echo "good luck"
	else
	    echo "Holberton School"
    fi
    ((i++ ))
done
