#!/usr/bin/env bash
# FizzBuzz
i=1
while [ $i -lt 100 ]
do
    a = i % 3
    b = i % 5
    if [ $a = 0 ]
    then
	if[ $b = 0 ]
	then
	    echo "FizzBuzz"
	else
	    echo "$i"
	fi
    else
	echo "Fizz"

    ((i++ ))
done
