#!/usr/bin/env bash
# This script shows the time for 12 hours and 59 minutes
h=0
m=0
a=0
echo "Hour: $h"
while [ $a -lt 766 ]
do
	((a++))
	((m++))
	echo $m
	if [ $m -eq 59 ]
	then
	    ((h++))
	    echo "Hour: $h"
	    m=0
	fi
done
((m++))
echo $m
